### ISSUE TITLE
Using Vue-Cytoscape with cytoscape context menus

### ISSUE THREAD

**Issue by kinuthiaduncan** [rcarcasses/vue-cytoscape#1]
Hello,
Thanks for the great work!
However, I have an issue with incorporating cytoscape context menus with vue-cytoscape.

**Comment by rcarcasses** [comment]
Hi @kinuthiaduncan, thanks for pointing this out. Can you provide further details about what you did and what failed?

**Comment by kinuthiaduncan** [comment]
Yes, this is what I am using

**Comment by kinuthiaduncan** [comment]
Great, thanks!

**Comment by rcarcasses** [comment]
Hi again,

So I have added two internal lifecycle hooks that you can use to register and configure extensions. I have updated the readme with the relevant information for you at the end, in particular there are two new example files that you can check how effectively use these lifecycle hooks. I have tested it with two different context menu extensions and everything seems to be properly working.

A package with the latest changes has been already published in npm (now version 0.1.2). Please check and let me know if you still have problems. I will close this issue but feel free to re-open it or create a new one.

**Comment by rcarcasses** [comment]
solved in  1935cb5,  version 0.1.2.

**Comment by kinuthiaduncan** [comment]
Works great
Thanks
