### ISSUE TITLE
Multiple Cytoscape instances (specify container)

### ISSUE THREAD

**Issue by zhjuve** [rcarcasses/vue-cytoscape#10]
Hi!
Thanks again for making expand collapse working!
I was trying to make several instances of component and though working it needs to be re-rendered and also plug-in installation bounds to single core instance (btw this also annoying when hot-reload works for dev server it errors with smth like "cannot bind <plugin> to core instance as already bound").

Could you please ability to specify container name in component code?
 div id="_cytoscape_" ref="cytoscape"
......
  async mounted () {
    // create a cytoscape instance using the referenced div
    const container = this.$refs._cytoscape_

**Comment by rcarcasses** [comment]
Hi @zhjuve, you're welcome, give me some days to think how to do this properly.

**Comment by emelendez** [comment]
Hi, that's exactly what i need... various cytoscape instances in their own "tab"... thanx in advanced!!

**Comment by zhjuve** [comment]
> Hi @zhjuve, you're welcome, give me some days to think how to do this properly.

Hi, is there any chance to look at that? Thanks.

**Comment by rcarcasses** [comment]
Hi @zhjuve, sorry to disappoint you but I haven't have time since recently I have had loads of work. It seems to me that we will need to change considerably how things are organised since this was thought to be used with one global instance. Anyway I'll try to do this, just don't know when.

If you have any idea, you are welcome to contribute!

**Comment by kondziu989** [comment]
Hi @zhjuve @rcarcasses @emelendez a
Have you somehow resolved this issue?

**Comment by rcarcasses** [comment]
Hi everyone, with version `v1.0.1` it is possible to have many cytoscape instances. Notice that the global reference `this.$cytoscape.instance` makes no longer sense in this case and has been deprecated. Please check the new api at [https://rcarcasses.github.io/vue-cytoscape](https://rcarcasses.github.io/vue-cytoscape).

I'll close this issue now but please do not hesitate to reopen it if you consider this is not enough or open new ones. Thanks for your patience.

**Comment by zhjuve** [comment]
That's superb! Thanks a lot!

**Comment by emelendez** [comment]
thanxs a lot, I'll give it a try...
