### ISSUE TITLE
Cant set image to the object

### ISSUE THREAD

**Issue by calebeaires** [rcarcasses/vue-cytoscape#13]
I tried to change the background to use an PNG picture in replace of color, but it does not work. Here is how I am doing:

```js
  .selector('node[client = "mysql"][sourceType = "database"]')
  .css({
    'background-image': './assets/flow/bg-mysql.png'
  })
```
**I have used this aproach on pure javascript and it does work, but right now it does not.**

There is no image with your plugin
<img width="377" alt="Screen Shot 2019-04-16 at 10 14 40" src="https://user-images.githubusercontent.com/794195/56212471-78a09f80-6030-11e9-8bc8-9755d7ee1ee6.png">

Here is done with pure javascript
<img width="185" alt="Screen Shot 2019-04-16 at 10 15 25" src="https://user-images.githubusercontent.com/794195/56212553-a1289980-6030-11e9-8506-1ec121bec420.png">

**Comment by rcarcasses** [comment]
Hi,

It is certainly possible to set background images with this plugin, I'm currently working on a project that does precisely that. It may be the case that your issue is likely to be related with webpack asset resolution, as I can guess from your code.

this may work for you, as it works for me:
```
import bg from './assets/flow/bg-mysql.png'
...
.css({
    'background-image':  bg
  })
```

**Comment by calebeaires** [comment]
Thanks. That worked. As I am using vue + typescript, I had to declare *.png on a *d.ts file: 

```ts
declare module "*.png" {
  const content: string;
  export default content;
}
```

**Comment by rcarcasses** [comment]
I'll close this, since it was not really an issue.
