### ISSUE TITLE
项目克隆完后，怎么查看效果

### ISSUE THREAD

**Issue by herosPan** [rcarcasses/vue-cytoscape#15]
我看到代码有很多功能，但我克隆下来，启动智能看到简单的展示
![TIM截图20190418191228](https://user-images.githubusercontent.com/39436000/56357460-6a0fdf00-620e-11e9-86f9-812b4c8910e5.png)

**Comment by rcarcasses** [comment]
English please :)

**Comment by rcarcasses** [comment]
yes, that is what you are supposed to see.

**Comment by herosPan** [comment]
![TIM截图20190418192225](https://user-images.githubusercontent.com/39436000/56357797-54e78000-620f-11e9-9ee3-e89774b557cd.png)

Are these examples not visual?

**Comment by rcarcasses** [comment]
these are other examples you can try, you have to modify the `src/main.js` file to include one of these components instead the default `App`.

**Comment by herosPan** [comment]
thank you very much
