### ISSUE TITLE
How to unregister the extension

### ISSUE THREAD

**Issue by herosPan** [rcarcasses/vue-cytoscape#16]
If not unregistered the extension might get registered again while development, causing this error:
Can not register `cxtmenu` for `core` since `cxtmenu` already exists in the prototype and can not be overridden

**Comment by herosPan** [comment]
preConfig(cytoscape) {
      console.log("calling pre-config", config);
      // cytoscape: this is the cytoscape constructor
      // cytoscape.use(cola);
      // cytoscape.use(cxtmenu);
      // cytoscape.use(edgehandles);
      if (typeof cytoscape('core', 'cola') !== 'function') {
        cytoscape.use(cola);
      }
      if (typeof cytoscape('core', 'cxtmenu') !== 'function') {
        cytoscape.use(cxtmenu);
      }
      // register edgehandles extension
      if (typeof cytoscape('core', 'edgehandles') !== 'function') {
        cytoscape.use(edgehandles)
      }
    }

**Comment by herosPan** [comment]
This can solve multiple registration problems, but the extension will fail.

**Comment by EHadoux** [comment]
Can't we get the ```cytoscape``` object through a call to ```VueCytoscape``` so we can register the extensions at the same place we ```Vue.use(VueCytoscape)``` and not in the preConfig?

**Comment by rcarcasses** [comment]
Hi @EHadoux, what you said it makes sense for me. Nevertheless this somehow enters in conflict with the request #10  to have several instances of `vue-cytoscape` in the same application, since this will basically force all the instances to register the same set of extensions.

Anyway I'll keep this in mind, you are welcome to contribute!

**Comment by EHadoux** [comment]
Fair enough.
In any case, if think it's better to not register it twice than to unregister then re-register.
Just checking with: 
```javascript 
preConfig(cytoscape) {
  if (!cytoscape('core', 'cxtmenu') {
    cytoscape.use(cxtmenu);
  }
}
```
is enough.
Might be good to specify it in the doc though. I'll try to think about a more elegant way to do it but it seems that cytoscapejs itself does not allow for unregistering so it might be the best way to avoid the error.

Another way might be to do the registering not directly on the cytoscape object but through a function that would be added to it (or passed as a second argument to preConfig) so this function could cache the registered extension and decide whether or not to actually register it. Something like:
```javascript
preConfig(cytoscape, register) {
  register('cxtmenu', cxtmenu);
}
```
(or alternatively ```cytoscape.register('cxtmenu', cxtmenu)``` added to the cytoscape object)
And this function would be:
```javascript
register(name, ext) {
  if (!this.registered.include(name)) {
    cytoscape.use(ext);
    this.registered.push(name);
  }
}
```
Not sure it's really better though.

**Comment by rcarcasses** [comment]
I like more the second approach, we could have a dictionary with the modules that has been registered up to the moment. Nevertheless, bear in mind that there are several ways to register an extension, take [this](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus) for instance, you can either register the extension doing `cytoscape.use(contextMenus, $)` if using `ES6` or `contextMenus( cytoscape, jquery )` if using `CommonJS`. 

The idea of providing hooks here was precisely to not to have an opinion about how you should register your extensions but rather to give you an space where you can actually do it the way the extension's author(s) suggest. Recall that `vue-cytoscape` is a wrapper library, not the library itself, so I think is better (out of its scope actually) to not to enforce people to do things in an opinionated way.

**Comment by EHadoux** [comment]
You are right, I'll stick to the test in the ```preConfig``` then.

**Comment by VitaliyDemchuk** [comment]
> preConfig(cytoscape) {
> console.log("calling pre-config", config);
> // cytoscape: this is the cytoscape constructor
> // cytoscape.use(cola);
> // cytoscape.use(cxtmenu);
> // cytoscape.use(edgehandles);
> if (typeof cytoscape('core', 'cola') !== 'function') {
> cytoscape.use(cola);
> }
> if (typeof cytoscape('core', 'cxtmenu') !== 'function') {
> cytoscape.use(cxtmenu);
> }
> // register edgehandles extension
> if (typeof cytoscape('core', 'edgehandles') !== 'function') {
> cytoscape.use(edgehandles)
> }
> }

Work for me. Thx!
