### ISSUE TITLE
The layout in the config does not take effect when using cy-element

### ISSUE THREAD

**Issue by herosPan** [rcarcasses/vue-cytoscape#18]
When using cy-element, if the elements data has no position, how do you need to automatically lay out

**Comment by rcarcasses** [comment]
See #17, there is a great explanation on the beginning. Basically you will have to mark `afterCreated` as `async`:

```
async after() {
  const cy = await this.$cytoscape.instance;
  cy.layout({
    name: 'breadthfirst',
    circle: false,
    roots: '#existingnode',
    spacingFactor: 1,
    padding: 50,
    fit: true,
  }).run();
}
```

**Comment by herosPan** [comment]
Can be laid out after modification, but only the first time can be accessed, switch routing access again, can not see the map

**Comment by herosPan** [comment]
I want to know how you initialized it, I can only come out when the chart is first accessed.

![TIM截图20190505190318](https://user-images.githubusercontent.com/39436000/57203510-4527b400-6fe3-11e9-9588-3e8a74c2297c.png)
