### ISSUE TITLE
Running the layout in the afterCreated when using cy-elements

### ISSUE THREAD

**Issue by herosPan** [rcarcasses/vue-cytoscape#19]
```
<cytoscape :preConfig="preConfig" :config="config" :afterCreated="after">
    <cy-element v-for="def in elements" :key="`${def.data.id}`" :definition="def"/>
  </cytoscape>

async after() {
  const cy = await this.$cytoscape.instance;
  cy.layout({
    name: 'breadthfirst',
    circle: false,
    roots: '#existingnode',
    spacingFactor: 1,
    padding: 50,
    fit: true,
  }).run();
}
```

I want to know how you initialized it, I can only come out when the chart is first accessed.Visit the following error again when accessing

![TIM截图20190505190318](https://user-images.githubusercontent.com/39436000/57265306-9f8b4800-70a9-11e9-845f-39bfe03765fc.png)

**Comment by rcarcasses** [comment]
See an example here [src/LayoutExtensionsWithCyElementsExample.vue](https://github.com/rcarcasses/vue-cytoscape/blob/master/src/LayoutExtensionsWithCyElementsExample.vue), you are doing something wrong.
