### ISSUE TITLE
Issue when included via webpack in production mode

### ISSUE THREAD

**Issue by steve-heine** [rcarcasses/vue-cytoscape#2]
With a vue-cli webpack option, on a run build i'm getting the following error

TypeError: e.registerBinding is not a function
    at vue-cytoscape.js:formatted:1
    at vue-cytoscape.js:formatted:1
    at _.a.load (vue-cytoscape.js:formatted:1)
    at _.s.notify (vue-cytoscape.js:formatted:1)
    at u.notify (vue-cytoscape.js:formatted:1)
    at u.initRenderer (vue-cytoscape.js:formatted:1)
    at new u (vue-cytoscape.js:formatted:1)
    at s (vue-cytoscape.js:formatted:1)
    at Object.setConfig (vue-cytoscape.js:formatted:1)
    at a.mounted (vue-cytoscape.js:formatted:1)

Everything works fine in run dev mode.

i'm not getting much traction on a workaround/fix yet.

this.$cytoscape is undefined.

Any ideas?

**Comment by rcarcasses** [comment]
Hi, sorry for the late reply, can you provide a small testable example so I can reproduce it? Thank you for your patience.

**Comment by steve-heine** [comment]
Not a problem, I think it may actually be related to the specific build of
cytoscape, and is resolved in the next release. I tested your code as a
regular component and it worked fine. Cytoscape has a known bug for that
version when running webpack with broken polyfills, so i suspect I may be
hitting that.

I’ll try and get an example thrown together later, hopefully tonight.

**Comment by rcarcasses** [comment]
Okay thank you, I'm eager to see, it may be the case that I shipped a wrong configuration.

**Comment by rcarcasses** [comment]
Any news on this gentleman? Can you provide a reproducible example?

**Comment by wooter-s** [comment]
Same problem；Have you solve the problem?
In my local development is ok;Via webpack to build online; throw err

`TypeError: e.registerBinding is not a function
    at monitorDetail.fa9e4fc1ed86a0232e93.js:1
    at monitorDetail.fa9e4fc1ed86a0232e93.js:1
    at T.a.load (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at T.l.notify (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at u.notify (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at u.initRenderer (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at new u (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at s (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at t.value (monitorDetail.fa9e4fc1ed86a0232e93.js:1)
    at e.notifyAll (common.fa9e4fc1ed86a0232e93.js:1)`

**Comment by Feng-ChuanJiang** [comment]
是的，我也遇到这个问题，有解决方案吗

**Comment by rcarcasses** [comment]
Okay, I just created a new project with the latest vue-cli, imported vue-cytoscape, put some dummy code inside and build it for production and all seems to be fine. I'm not sure but this may be related to webpack configuration you are using, for building I just invoked *yarn build* which is just a call to "vue-cli-service build". You can find the source code of the example here:

[`https://github.com/rcarcasses/vue-cytoscape-test`](https://github.com/rcarcasses/vue-cytoscape-test)

I'll need further information about this issue to figure out precisely your build problem.

Hope the example serves you as a good starting code for your work.

**Comment by rcarcasses** [comment]
This doesn't seem like a *vue-cytoscape* issue but a webpack build config. If you experience the same problem and you are willing to share a concrete example then feel free to open a new issue.

**Comment by wiredgril666** [comment]
请问解决这个问题了吗？我也遇到了这个问题。开发环境是正常的。然后用webpack 打包后就不行了。@Feng-ChuanJiang

**Comment by wiredgril666** [comment]
@Feng-ChuanJiang不过我是用的cytoscape,js 也不是用vue，是用react开发的

**Comment by Feng-ChuanJiang** [comment]
@wiredgril666  我换成官方的引入方式了

**Comment by wiredgril666** [comment]
@Feng-ChuanJiang 哪种是官方的引入方式啊

**Comment by Feng-ChuanJiang** [comment]
@wiredgril666  以前我是用的是npm i vue-cytoscape这种方式，换成了npm i cytoscape
