### ISSUE TITLE
Switch routing graph display problem

### ISSUE THREAD

**Issue by herosPan** [rcarcasses/vue-cytoscape#23]
When using the cy element, the graphics cannot be loaded for the second time, and the graphics can only be loaded each time the page is refreshed.

 <cytoscape
            :config="config"
            :preConfig="preConfig"
            :afterCreated="afterCreated"
          >
            <cy-element
              v-for="def in elements.nodes"
              :key="`${def.data.id}`"
              :definition="def"
            />
            <cy-element
              v-for="def in elements.edges"
              :key="`${def.data.id}`"
              :definition="def"
            />
          </cytoscape>

preConfig(cytoscape) {
      console.log("calling pre-config", config, elements);
      // cytoscape: this is the cytoscape constructor
      if (!cytoscape('core', 'cola')) {
        cytoscape.use(cola);
      }
    },
    async afterCreated() {
      console.log("after created")
      const cy = await this.$cytoscape.instance
      cy.elements()
        .layout({ name: "cola" })
        .run();
    }

**Comment by bkuker** [comment]
@herosPan Did you find a solution? I think this is affecting me as well, but while developing using vue-cli serve and the live updates.

**Comment by Inzeppelin** [comment]
@herosPan, plus one, did you resolve this one? If so, please, share the solution

**Comment by bkuker** [comment]
@Inzeppelin What's the problem you are having? We should probably open a ticket, the dev of this component seems pretty responsive.

**Comment by Agostin** [comment]
Hello there! Any solution found? I unfortunately have the same issue :/

**Comment by rcarcasses** [comment]
@Agostin can you provide a testable repo example with the issue you are experiencing? beware that you have add/remove `cy-elements` and change their keys in order to trigger an update, this is how `vue` works.

**Comment by mfigueredo** [comment]
Is there any update about the solution in this case? My problem is similar. When I open the route where I use vue-cytoscape it works fine. However, if swtiching to another route and after back to the original route the vue-cytoscape is not able to plot the new nodes added. Is there some rule for reload the component related to vue-cytoscape?

Thanks in advice.
