### ISSUE TITLE
Errors while using example code in nuxt

### ISSUE THREAD

**Issue by aoighost** [rcarcasses/vue-cytoscape#35]
I'm trying to use the example code in nuxt from codepen and I'm having errors pop up in the console and it's refusing to render the graph. I have no idea what's going wrong here.

The errors are
 [Vue warn]: Injection "cy" not found

found in

---> <CyElement>
       <Pages\knowledgegraph.vue> at pages\knowledgegraph.vue
         <Nuxt>
           <VContent>
             <VApp>
               <Default> at layouts\default.vue
                 <Root>

[Vue warn]: Error in data(): "TypeError: Cannot read property 'then' of undefined"

found in

---> <CyElement>
       <Pages\knowledgegraph.vue> at pages\knowledgegraph.vue
         <Nuxt>
           <VContent>
             <VApp>
               <Default> at layouts\default.vue
                 <Root>

TypeError: Cannot read property 'then' of undefined
    at new CyElement

**Comment by aoighost** [comment]
This is the code
`<template>
  <div id="app" class="fullscreen" @load="calculateHeightAndWidth()">
<cytoscape ref="cy" :config="config" v-on:mousedown="addNode" v-on:cxttapstart="updateNode">
  <cy-element
    v-for="def in elements"
    :key="`${def.data.id}`"
    :definition="def"
    v-on:mousedown="deleteNode($event, def.data.id)"
  />
</cytoscape>
  </div>
</template>

<script>
import config from './example-config'

const elements = [...config.elements]
delete config.elements

export default {
  data () {
    return {
      config,
      elements
    }
  },
  methods: {
    addNode (event) {
      console.log(event.target, this.$refs.cyRef.instance)
      if (event.target === this.$refs.cyRef.instance) {
        console.log('adding node', event.target)
      }
    },
    deleteNode (id) {
      console.log('node clicked', id)
    },
    updateNode (event) {
      console.log('right click node', event)
    },
    preConfig (cytoscape) {
      console.log('calling pre-config', cytoscape)
    },
    afterCreated (cy) {
      // cy: this is the cytoscape instance
      console.log('after created', cy)
    }
  }
}
</script>

<style>
@import url('https://fonts.googleapis.com/css?family=PT+Sans');

body{
  font-family: 'PT Sans', sans-serif;
  background-color: #eee;
}
.title{
  position:absolute;
  text-align: center;
  left: 2em;
}
h1,a{
  color: #1aad8d;
  text-decoration: none;
}

ul.menu {
  list-style: none;
  position: absolute;
  z-index: 100;
  min-width: 20em;
  text-align: left;
}
ul.menu li{
  margin-top: 1em;
  position: relative;
}

.node-label{
  fill: white;
  font-size: 1em;
}
.link-label{
  fill: purple;
  transform: translate(0,.5em);
  font-size: .8em;
}
.fullscreen {
  height: calc(100% - 96px);
  width: calc(100%);
  position: relative;
  min-height: 100%;
  min-width: 100%;
}
.net {
  min-height: calc(100vh);
  min-width: calc(100vw)
  ;
}
</style>`

**Comment by rcarcasses** [comment]
Hi @aoighost, thanks for pointing this out. I'm not sure why this happens neither, but seems like a real issue, I'll keep it in mind. I'll let you know if I find a solution.

**Comment by joshdvir** [comment]
Faced the same issue today using Vue 2.6.6, upgrade to Vue 2.6.10 solved it.

**Comment by aoighost** [comment]
So upgrading to nuxt and vue latest, I now get errors on starting with the following:

  5:7  error  Parsing error: Unexpected token                                                                           
  3 |        <cytoscape                                                                                                   4 |       ref="cyRef"                                                                                                 > 5 |       :config="config"                                                                                                |       ^                                                                                                             6 |       v-on:mousedown="addNode"                                                                                      7 |       v-on:cxttapstart="updateNode"                                                                                 8 |     >                                                                                                             
✖ 1 problem (1 error, 0 warnings)                                                                                      

as well as stylus issues. I think something big broke.

**Comment by aoighost** [comment]
that jumbled it, here's a pic
https://imgur.com/a/es3MsCT

@joshdvir any chance you can share a working code snippet for how to load cytoscape?

@rcarcasses any chance you can make a code example in a demo folder that shows how to do it without using codepen or anything like that?

**Comment by joshdvir** [comment]
@aoighost Here is my code

```
<cytoscape
            ref="cyRef"
            :config="cyConfig"
            v-on:mousedown="addNode"
            v-on:cxttapstart="updateNode"
            :afterCreated="afterCreated"
            :preConfig="preConfig"
          >
            <cy-element
              v-for="def in resources"
              :key="def.data.id"
              :definition="def"
              class="node-background-img-2"
              v-on:mousedown="deleteNode($event, def.data.id)"
              :sync="true"
            />
          </cytoscape>
```

This is in data()
```
cyConfig: {
        boxSelectionEnabled: false,
        autounselectify: true,
        style: [
          {
            selector: "node",
            style: {
              "background-color": "#666",
              label: "data(name)"
            }
          },
          {
            selector: "edge",
            style: {
              width: 3,
              "line-color": "#ccc",
              "target-arrow-color": "#ccc",
              "target-arrow-shape": "triangle"
            }
          },
          {
            selector: "#1",
            css: {
              "background-image": "/img/icons/IoT_Sensor_dark-bg.svg"
            }
          },
          {
            selector: ".node-background-img-2",
            css: {
              "background-image": "/img/icons/IoT_Windfarm_dark-bg.svg"
            }
          }
        ],
        layout: {
          name: "cose",
          padding: 60,
          randomize: true,
          componentSpacing: 40,
        },
      },
```

This loads without issues

**Comment by aoighost** [comment]
Thanks, I got it working as well. Had to redo the nuxt project because things were way out of date and needed migrating. There were some linter issues that needed fixing as well.
