### ISSUE TITLE
Context menu not opening from example

### ISSUE THREAD

**Issue by aoighost** [rcarcasses/vue-cytoscape#36]
Hey, I'm trying to open the context menu based on the documentation example in a nuxt/vuetify project and i click and the context menu doesn't open. It appears as though cxtmenu from cytoscape also has the same problem and I'm not sure why it's not popping up the context menus.

**Comment by aoighost** [comment]
So here's the code

https://gist.github.com/aoighost/7ebb5b6d2312bfbcd12b91003590d78a

it renders the graph, but I also noticed it doesn't console log the id of the node when I click nodes.

**Comment by aoighost** [comment]
OK, so I partially solved the problem. I didn't add pre config and after created to cytoscape in the template. That being said, now it's saying that context menu already exists in the prototype and errors out.

**Comment by aoighost** [comment]
Error: Can not register `contextmenu` for `core` since `contextmenu` already exists in the prototype and can not be overridden

**Comment by aoighost** [comment]
Just found the answer here:
https://github.com/cytoscape/cytoscape.js-panzoom/issues/19

It's working now.

**Comment by rcarcasses** [comment]
good to hear that you figured out by yourself :)
