### ISSUE TITLE
Layout Extensions

### ISSUE THREAD

**Issue by m-wrzr** [rcarcasses/vue-cytoscape#4]
Hey, thanks for this library!

I have a question regarding cytoscape layout extensions: is it possible to use them directly within vue-cytoscape? And if so how?
The recommended import as described in e.g. https://github.com/cytoscape/cytoscape.js-cola doesn't work for me.

Sry, relatively new to Vue/Javascript in general..

**Comment by rcarcasses** [comment]
Hey @m-wrzr, I just created a sample project with your desired configuration. Basically to use `cytoscape` plugins you have to hook into the lifecycle methods `preConfig` and `afterCreated`. Take a look here:

https://github.com/rcarcasses/vue-cytoscape-cola

Enjoy!

**Comment by m-wrzr** [comment]
Thank you so much!!

Created a PR to integrate this example into the main repo #5

**Comment by rcarcasses** [comment]
Well done, thank you!
