### ISSUE TITLE
Element height hard-coded to 600px. Seriously?

### ISSUE THREAD

**Issue by dataway** [rcarcasses/vue-cytoscape#47]
The element size is hard coded, in particular the height is set to 600px. Come on man.

https://github.com/rcarcasses/vue-cytoscape/blob/58af89b97a528bda9b1e20ed48822d3e6c499077/src/components/Cytoscape.ts#L28

**Comment by rcarcasses** [comment]
it is the minimum height possible, not the height what is set, moreover you can override this, this helps a lot as it happens that many css framework will give zero height by default to the component and you see nothing.

I encourage you to be more constructive next time you open an issue.

**Comment by andradf** [comment]
Any suggestions on how to override it? From the outside of the Cytoscape component we don't have direct access to the container element.

**Comment by rcarcasses** [comment]
I think you can write like:

```
# cytoscape-div {
    width: 1000px;
}
```
let me know if it works for you.

**Comment by mfigueredo** [comment]
A tried a lot of ways to override the min-height however without any sucess. The solution to put `width: 1000px;` does not work. I cannot override the heigth to my desired value because it is smaller than 600px. 

Any suggestion to this situation?
Thank in advice!

**Comment by rcarcasses** [comment]
Hi @mfigueredo, cytoscape is mounted in a `div` with id `cityscape-div`, so css rules should work, did you try this https://github.com/rcarcasses/vue-cytoscape/issues/47#issuecomment-564068790?

**Comment by rcarcasses** [comment]
Hi @mfigueredo, what about changing css at runtime?
```
document.getElementById("cytoscape-div").style.minHeight="100px";
```

**Comment by mfigueredo** [comment]
> Hi @mfigueredo, what about changing css at runtime?
> 
> ```
> document.getElementById("cytoscape-div").style.minHeight="100px";
> ```

This worked for me. Thank you a lot, @rcarcasses.
