### ISSUE TITLE
Elements not available in afterCreated

### ISSUE THREAD

**Issue by cosmorunner** [rcarcasses/vue-cytoscape#50]
I would like to cy.center() the graph after it has been initialized. I thought to put it into the afterCreated() hook but it is not working, even though the graph itself is loaded properly with layout and style. It just sticks in the top-right corner:
Note: `this.graphCalculated` is passed via a prop.

    <cytoscape ref="cy":config="config" :afterCreated="afterCreated">
        <cy-element
            v-for="def in [...this.graphCalculated.nodes, ...this.graphCalculated.edges]"
            :key="`${def.data.id}`"
            :definition="def"
            :sync="true"
        />
    </cytoscape>

In methods():

    afterCreated(cy) {
        console.log(cy.elements()); // No elements
        console.log(cy.center()); // Not working
    },

Sinde I am using the "preset" Layout, I also tried declaring a "ready" Layout-Callback, but its also does not work there. 
Where are the elements ? What am I missing?
Any help is appreciated!

**Comment by rcarcasses** [comment]
Hi @cosmorunner, I think the solution to your problem goes in the same line as in https://github.com/rcarcasses/vue-cytoscape/issues/49, could you try the solutions provided and let me know if it works for you?

Also `cy.elements()` is empty in `afterCreated` because `cytoscape` has been created, but elements haven't been added yet.

**Comment by cosmorunner** [comment]
Hi @rcarcasses! Thank you for your quick reply!
It works now with this solution:
At imports of component in which `<cytoscape :afterCreated=afterCreated>` and `<cy-element>` is placed:

    let resolveCy = null;
    export const cyPromise = new Promise(resolve => (resolveCy = resolve));

In methods:

    async afterCreated(cy) {
        resolveCy(cy);
            let cyReady = await cyPromise;
            cyReady.center(); // cyReady has all Elements now.
    }

Cheers!
