### ISSUE TITLE
Plugins such as cytoscape.js-edgehandles

### ISSUE THREAD

**Issue by ghamarian** [rcarcasses/vue-cytoscape#6]
How to make the interactive feature (<cy-element>) work with plugins such as edgehandles that they create elements internally?

**Comment by rcarcasses** [comment]
Hi @ghamarian, this is an interesting topic, this plugin allows the dynamic addition of edges to `cytoscape`, so at first glance will break the synchronisation with `vue-cytoscape`. Give me a few days and I'll try to do some modifications to allow the usage of such plugins seamlessly.

**Comment by ghamarian** [comment]
Thanks. My main goal is to create a similar product like this one: https://www.machine2learn.com/wp-content/uploads/2018/10/main.html

**Comment by rcarcasses** [comment]
Please take a look to the example in `src/EdgeHandlesExample.vue`, this contains the same example as the `demo` one promoted in the `cytoscape.js-edgehandles` repository. I have made a new release of the package that allows the synchronisation of the `cy-elements` with the ones created directly in `cytoscape` (for instance, those added while using the plugin). 

Notice though, that there are some issues with the plugin itself. It seems like when you enable/disable the drawing something spoils internally. One of the reasons I'm maintaining `vue-cytoscape` is precisely to create this kind of tools with the support of the `vue` ecosystem, particularly with support for `vuex`.

Do not forget to upgrade to `v0.2.4`, I hope you like it, enjoy!

**Comment by ghamarian** [comment]
Thanks!
