### ISSUE TITLE
URL broken 404 returned 

### ISSUE THREAD

**Issue by harissg** [rcarcasses/vue-cytoscape#83]
The URL provided in the docs returns a 404 HTTP response. 

```For more details please visit our site:```

```https://rcarcasses.github.com/vue-cytoscape```

Screengrab: 
![image](https://user-images.githubusercontent.com/16037654/127898807-6e0a8c2c-0d49-4de8-bf85-a30e88bcb1c0.png)

**Comment by thearod5** [comment]
Am I trying to find the documentation for this module as I have a legacy project using this module. Is there any one that can redirect me to the new website?

**Comment by rcarcasses** [comment]
https://rcarcasses.github.io/vue-cytoscape
