### ISSUE TITLE
Cytoscape freezes when adding elements after drag

### ISSUE THREAD

**Issue by vdechef** [rcarcasses/vue-cytoscape#9]
Using vue-cytoscape v0.2.5, vue-cytoscape freezes during "dragfree" event.
Using v0.2.3 I don't have this problem.
I forked your test project to reproduce this behavior: https://github.com/vdechef/vue-cytoscape-test

The problem occurs because I need to set the elements in cytoscape once a node is draged and released.
Using the project above, just drag a node twice and your browser should freeze (infinite loop).

FYI I use Firefox with debian.

**Comment by rcarcasses** [comment]
Hi @vdechef, thanks for reporting this, I'll take a look as soon as I have a chance.

**Comment by rcarcasses** [comment]
There was indeed a regression in the `v0.2.5`, version, I have fixed the problem in `v0.2.6`, you should update now. Thanks for pointing this out!
